<#
.SYNOPSIS
    Imports and restores a predefined Group Policy Object (GPO) set from backup into the current domain.
	
.DESCRIPTION
    The **AddAndImport_GPOSet.ps1** script automates the deployment of a predefined collection of Group Policy Objects (GPOs) 
    from a backup folder into an existing Active Directory environment.

    It parses a `manifest.xml` file generated by the Group Policy Management Console (GPMC) during backup to determine which GPOs 
    need to be created and imported. The script then:
    - Validates the current working directory and navigates to the Group Policy backup folder (`C:\_it\ADC_Setup\1_GroupPolicies`)
    - Reads and validates the XML manifest (`manifest.xml`) within the backup folder (`GPOSet_latest`)
    - Iterates through all listed GPOs, creating each policy in the domain if it doesn’t exist
    - Imports the GPO configuration from the backup set
    - Logs all operations, including errors, to a timestamped log file for traceability

    This script ensures that multiple GPOs can be restored or redeployed consistently across environments, 
    such as after domain rebuilds, test-to-production migrations, or new domain controller setups.

	Requirements:
	    - Windows Server 2016 or newer  
	    - PowerShell 5.1 or later  
	    - Active Directory Domain Services (ADDS) installed and configured  
	    - Group Policy Management Console (GPMC) installed  
	    - Administrative privileges on the domain  
	    - Valid GPO backup structure including a manifest.xml file  
	    - Execution policy allowing scripts (`Set-ExecutionPolicy Bypass`)  
	
.LINK
	https://learn.microsoft.com/en-us/powershell/module/grouppolicy/new-gpo  
    https://learn.microsoft.com/en-us/powershell/module/grouppolicy/import-gpo  
    https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/backup-gpo  
	https://github.com/PScherling
    
.NOTES
          FileName: AddAndImport_GPOSet.ps1
          Solution: Automated Group Policy Set Import and Deployment
          Author: Patrick Scherling
          Contact: @Patrick Scherling
          Primary: @Patrick Scherling
          Created: 2025-01-03
          Modified: 2025-01-03

          Version - 0.0.1 - () - Finalized functional version 1.
          Version - 0.0.2 - () - Reworked and little additions.

          TODO:
		  
		
.Example
	PS> powershell.exe -ExecutionPolicy Bypass -File "C:\Scripts\AddAndImport_GPOSet.ps1"
    Executes the script automatically during post-domain deployment, restoring all GPOs from backup.
#>

function Import-GPO-Set {
	# Log file path
    $logFile = "C:\_it\ADC_Setup\Logfiles\AddAndImport_GPOSet.log"
	
	# Function to log messages with timestamps
    function Write-Log {
        param (
            [string]$Message
        )
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $logMessage = "[$timestamp] $Message"
        #Write-Output $logMessage
        $logMessage | Out-File -FilePath $logFile -Append
    }
    
    # Start logging
    Write-Log " Starting configuration process..."
	
	Write-Log " Checking current location"
	$location = Get-Location
	if($location -ne "C:\_it\ADC_Setup\1_GroupPolicies"){
		Write-Log " Changing location to (C:\_it\ADC_Setup\1_GroupPolicies)"
		$location = "C:\_it\ADC_Setup\1_GroupPolicies"
	}
	else{
		#Nothing to do
		Write-Log " Location is correct."
	}
	$gpofolder = "EF_GPOSet_latest"
	$xmlname = "manifest.xml"
	
	Write-Log " Get-Location is: $location"
	Write-Log " GPO Folder is: $gpofolder"
	Write-Log " XML Manifest is: $xmlname"

	#Join to one full path
	Write-Log " Try to join to one full path"
	$gpofolderpath = Join-Path $location $gpofolder
	$fullxmlpath = Join-Path $gpofolderpath $xmlname
	
	Write-Log " Full Path to Manifest is: $fullxmlpath"
	Write-Host " Full Path to Manifest is: $fullxmlpath"

	if(Test-Path $fullxmlpath){
		Write-Log " Checking if the XML file exists and is a valid XML file"
		
		try{
		    [xml]$xml = Get-Content $fullxmlpath -Encoding UTF8 -ErrorAction Stop
		}
		catch {
			Write-Log " ERROR: Failed to parse XML file.
	Reason: $_"
			Write-Host -ForegroundColor Red " ERROR: Failed to parse XML file.
	Reason: $_"
		}
		
		$gpolist = @()
		foreach ($BackupInst in $xml.Backups.BackupInst){
			#Write-Host $BackupInst.GPODisplayName."#cdata-section"
			$gpolist += $BackupInst.GPODisplayName."#cdata-section"

		}
		
		$NumOfGPOs = $gpolist.Count
		
		Write-Log " There are $NumOfGPOs GPOs to process."
		Write-Host " There are $NumOfGPOs GPOs to process."
		
		foreach($gpo in $gpolist)
		{
			try {
				New-GPO -name $gpo
				Write-Log " Creating $gpo"
				Write-Host " Creating $gpo"
			}
			catch {
				Write-Log " ERROR: $gpo could not be created!
	Reason: $_"
				Write-Host -ForegroundColor Red " ERROR: $gpo could not be created!
	Reason: $_"
			}
			
			try {
				Import-GPO -BackupGpoName $gpo -TargetName $gpo -path $gpofolderpath
				Write-Log " Importing $gpo settings"
				Write-Host " Importing $gpo settings"
			}
			catch{
				Write-Log " ERROR: $gpo settings not imported!
	Reason: $_"
				Write-Host -ForegroundColor Red " ERROR: $gpo settings not imported!
	Reason: $_"
			}
		}
		
		Write-Log " $NumOfGPOs GPOs have been added."
		Write-Host " $NumOfGPOs GPOs have been added."
	}
	else{
		Write-Log " ERROR: XML File not found!" 
		Write-Host -ForegroundColor Red " ERROR: XML File not found!" 
	}

	Read-Host -Prompt " Press any key"
}


Import-GPO-Set
